package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Doctor generated by hbm2java
 */
public class Doctor implements java.io.Serializable {

	private int doctorId;
	private String doctorName;

	public Doctor() {
	}

	public Doctor(int doctorId) {
		this.doctorId = doctorId;
	}

	public Doctor(int doctorId, String doctorName) {
		this.doctorId = doctorId;
		this.doctorName = doctorName;
	}

	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

}
