package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Emailgroup generated by hbm2java
 */
public class Emailgroup implements java.io.Serializable {

	private int id;
	private String name;

	public Emailgroup() {
	}

	public Emailgroup(int id) {
		this.id = id;
	}

	public Emailgroup(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
