package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private EmpId id;

	public Emp() {
	}

	public Emp(EmpId id) {
		this.id = id;
	}

	public EmpId getId() {
		return this.id;
	}

	public void setId(EmpId id) {
		this.id = id;
	}

}
