package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * EmployeeData generated by hbm2java
 */
public class EmployeeData implements java.io.Serializable {

	private int id;
	private Date dob;
	private int age;
	private String employeeName;
	private String ssn;
	private String type;
	private Integer cardId;

	public EmployeeData() {
	}

	public EmployeeData(int id, int age, String ssn) {
		this.id = id;
		this.age = age;
		this.ssn = ssn;
	}

	public EmployeeData(int id, Date dob, int age, String employeeName, String ssn, String type, Integer cardId) {
		this.id = id;
		this.dob = dob;
		this.age = age;
		this.employeeName = employeeName;
		this.ssn = ssn;
		this.type = type;
		this.cardId = cardId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

}
