package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * EmployeeDataEmailgroup generated by hbm2java
 */
public class EmployeeDataEmailgroup implements java.io.Serializable {

	private EmployeeDataEmailgroupId id;

	public EmployeeDataEmailgroup() {
	}

	public EmployeeDataEmailgroup(EmployeeDataEmailgroupId id) {
		this.id = id;
	}

	public EmployeeDataEmailgroupId getId() {
		return this.id;
	}

	public void setId(EmployeeDataEmailgroupId id) {
		this.id = id;
	}

}
