package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Paystub generated by hbm2java
 */
public class Paystub implements java.io.Serializable {

	private int id;
	private Date end;
	private Date start;
	private float salary;
	private Integer paystubFor;

	public Paystub() {
	}

	public Paystub(int id, float salary) {
		this.id = id;
		this.salary = salary;
	}

	public Paystub(int id, Date end, Date start, float salary, Integer paystubFor) {
		this.id = id;
		this.end = end;
		this.start = start;
		this.salary = salary;
		this.paystubFor = paystubFor;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public float getSalary() {
		return this.salary;
	}

	public void setSalary(float salary) {
		this.salary = salary;
	}

	public Integer getPaystubFor() {
		return this.paystubFor;
	}

	public void setPaystubFor(Integer paystubFor) {
		this.paystubFor = paystubFor;
	}

}
