package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int id;
	private String course;
	private int rollNumber;
	private String studentName;

	public Student() {
	}

	public Student(int id, int rollNumber) {
		this.id = id;
		this.rollNumber = rollNumber;
	}

	public Student(int id, String course, int rollNumber, String studentName) {
		this.id = id;
		this.course = course;
		this.rollNumber = rollNumber;
		this.studentName = studentName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public int getRollNumber() {
		return this.rollNumber;
	}

	public void setRollNumber(int rollNumber) {
		this.rollNumber = rollNumber;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

}
