package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * StudentStudentcertificationId generated by hbm2java
 */
public class StudentStudentcertificationId implements java.io.Serializable {

	private int studentStudentId;
	private int studentCertificationCertificationId;

	public StudentStudentcertificationId() {
	}

	public StudentStudentcertificationId(int studentStudentId, int studentCertificationCertificationId) {
		this.studentStudentId = studentStudentId;
		this.studentCertificationCertificationId = studentCertificationCertificationId;
	}

	public int getStudentStudentId() {
		return this.studentStudentId;
	}

	public void setStudentStudentId(int studentStudentId) {
		this.studentStudentId = studentStudentId;
	}

	public int getStudentCertificationCertificationId() {
		return this.studentCertificationCertificationId;
	}

	public void setStudentCertificationCertificationId(int studentCertificationCertificationId) {
		this.studentCertificationCertificationId = studentCertificationCertificationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentStudentcertificationId))
			return false;
		StudentStudentcertificationId castOther = (StudentStudentcertificationId) other;

		return (this.getStudentStudentId() == castOther.getStudentStudentId()) && (this
				.getStudentCertificationCertificationId() == castOther.getStudentCertificationCertificationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentStudentId();
		result = 37 * result + this.getStudentCertificationCertificationId();
		return result;
	}

}
