package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Studentaddress generated by hbm2java
 */
public class Studentaddress implements java.io.Serializable {

	private int addressId;
	private String address;

	public Studentaddress() {
	}

	public Studentaddress(int addressId) {
		this.addressId = addressId;
	}

	public Studentaddress(int addressId, String address) {
		this.addressId = addressId;
		this.address = address;
	}

	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
