package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * StudentStudentcertification generated by hbm2java
 */
public class StudentStudentcertification implements java.io.Serializable {

	private StudentStudentcertificationId id;

	public StudentStudentcertification() {
	}

	public StudentStudentcertification(StudentStudentcertificationId id) {
		this.id = id;
	}

	public StudentStudentcertificationId getId() {
		return this.id;
	}

	public void setId(StudentStudentcertificationId id) {
		this.id = id;
	}

}
