package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Studentcertification generated by hbm2java
 */
public class Studentcertification implements java.io.Serializable {

	private int certificationId;
	private String certificationName;

	public Studentcertification() {
	}

	public Studentcertification(int certificationId) {
		this.certificationId = certificationId;
	}

	public Studentcertification(int certificationId, String certificationName) {
		this.certificationId = certificationId;
		this.certificationName = certificationName;
	}

	public int getCertificationId() {
		return this.certificationId;
	}

	public void setCertificationId(int certificationId) {
		this.certificationId = certificationId;
	}

	public String getCertificationName() {
		return this.certificationName;
	}

	public void setCertificationName(String certificationName) {
		this.certificationName = certificationName;
	}

}
