package org.hibernate;
// Generated Aug 6, 2021, 12:56:23 PM by Hibernate Tools 5.4.30.Final

/**
 * Studentdetail generated by hbm2java
 */
public class Studentdetail implements java.io.Serializable {

	private int studentId;
	private String studentMobileNumber;

	public Studentdetail() {
	}

	public Studentdetail(int studentId) {
		this.studentId = studentId;
	}

	public Studentdetail(int studentId, String studentMobileNumber) {
		this.studentId = studentId;
		this.studentMobileNumber = studentMobileNumber;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getStudentMobileNumber() {
		return this.studentMobileNumber;
	}

	public void setStudentMobileNumber(String studentMobileNumber) {
		this.studentMobileNumber = studentMobileNumber;
	}

}
